# Generated by Django 4.2.2 on 2023-07-31 18:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTypes',
            fields=[
                ('type_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTitles',
            fields=[
                ('title_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('title_description', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('engagement_id', models.AutoField(primary_key=True, serialize=False)),
                ('engagement_srg_id', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('fye', models.DateField(blank=True, null=True)),
                ('budget_amount', models.IntegerField(default=10000, null=True)),
                ('budget_hours', models.IntegerField(default=120)),
                ('is_complete', models.BooleanField(default=False)),
                ('complete_date', models.DateField(blank=True, default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('expense_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_category', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'ordering': ['expense_category_id'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['parent_id'],
            },
        ),
        migrations.CreateModel(
            name='Timecode',
            fields=[
                ('time_code', models.IntegerField(primary_key=True, serialize=False)),
                ('time_code_desc', models.TextField(blank=True, max_length=75, null=True)),
                ('time_code_hours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['time_code'],
            },
        ),
        migrations.CreateModel(
            name='TimeType',
            fields=[
                ('time_type_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('time_type_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('todolist_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_date', models.DateField(default=datetime.date(2023, 7, 31))),
                ('anticipated_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note', models.TextField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('engagement', models.ForeignKey(db_column='srg_id', on_delete=django.db.models.deletion.CASCADE, to='app.engagement')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2023, 7, 31))),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('engagement', models.ForeignKey(db_column='srg_id', on_delete=django.db.models.deletion.CASCADE, to='app.engagement')),
                ('time_type_id', models.ForeignKey(default='B', on_delete=django.db.models.deletion.CASCADE, to='app.timetype')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parent')),
            ],
            options={
                'ordering': ['provider_id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2023, 7, 31))),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.engagement')),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.expensecategory')),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parent'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.provider'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='time_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.timecode'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.billingtypes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeetitles'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.engagement')),
            ],
        ),
    ]
