# Generated by Django 4.2.2 on 2023-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_engagement_engagement_hourly_rate_engagement_is_rac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='is_rac',
            field=models.BooleanField(default=True),
        ),
    ]
