# Generated by Django 4.2.2 on 2023-08-17 14:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_engagement_is_rac'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='todo_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagement_hourly_rate',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 17)),
        ),
        migrations.AlterField(
            model_name='time',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 17)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date',
            field=models.DateField(default=datetime.date(2023, 8, 17)),
        ),
    ]
