# Generated by Django 4.2.2 on 2023-09-18 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_time_date_time_ts_date_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ts_is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 18)),
        ),
        migrations.AlterField(
            model_name='time',
            name='ts_date',
            field=models.DateField(default=datetime.date(2023, 9, 18)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date',
            field=models.DateField(default=datetime.date(2023, 9, 18)),
        ),
    ]
