# Generated by Django 4.2.2 on 2023-11-08 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_employee_ts_is_submitted_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name='time',
            name='ts_date',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date',
            field=models.DateField(default=datetime.date(2023, 11, 8)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date_end',
            field=models.DateField(blank=True, default=datetime.date(2023, 11, 8), null=True),
        ),
    ]
