# Generated by Django 4.2.2 on 2023-12-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_expense_time_type_id_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
        migrations.AlterField(
            model_name='time',
            name='ts_date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date',
            field=models.DateField(default=datetime.date(2023, 12, 13)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date_end',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 13), null=True),
        ),
    ]
