# Generated by Django 4.2.2 on 2023-12-15 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_engagement_alert_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='time',
            name='ts_date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date_end',
            field=models.DateField(blank=True, default=datetime.date(2023, 12, 15), null=True),
        ),
        migrations.CreateModel(
            name='EngagementNotes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_date', models.DateField(default=datetime.date(2023, 12, 15))),
                ('note', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.engagement')),
            ],
        ),
    ]
