# Generated by Django 4.2.2 on 2024-07-06 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_expense_date_alter_time_ts_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_billable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='engagementnotes',
            name='note_date',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='time',
            name='ts_date',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date',
            field=models.DateField(default=datetime.date(2024, 7, 5)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='todo_date_end',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 5), null=True),
        ),
    ]
